### ISSUE TITLE
One column per line for GROUP BY clauses

### ISSUE THREAD

**Issue by dogan-sky** [Matts966/zetasql-formatter#10]
Hi @Matts966 !

Thank you so much for the previous change on formatting rules for `WHERE` and `ON` (issue #6).

That change has also introduced new formatting for `GROUP BY` clauses. All `GROUP BY` columns seem to be on a single line.

Is it possible to revert the `GROUP BY` formatting so that there is one column per line, like the example below ?

よろしくお願いします。

```sql
SELECT
  *
FROM
  foo.bar_tab1
LEFT JOIN
  foo.bar_tab2
ON
  foo.bar_tab1.id = foo.bar_tab2.id
WHERE
  col1 = 'abc'
  AND col2 > 10
  AND col3 IS NOT NULL
GROUP BY
  1, 
  x, 
  y, 
  z;
```

**Comment by Matts966** [comment]
Hi! Thank you for your conrtibution!

@dogan-sky 
How about automatically sorting columns and formatting column words per line, column numbers in a line.

## from

```
SELECT
  *
GROUP BY
  x, y, z, 1, 2;
```

## to

```
SELECT
  *
GROUP BY
  1, 2, 
  x,
  y,
  z;
```

**Comment by dogan-sky** [comment]
That sounds good, thanks @Matts966 :)
