### ISSUE TITLE
Unable to format QUALIFY clause

### ISSUE THREAD

**Issue by codepozro** [Matts966/zetasql-formatter#12]
zetasql-formatter fails on [`QUALIFY` clause](https://cloud.google.com/bigquery/docs/reference/standard-sql/query-syntax#qualify_clause) with syntax error. 

For example, formatting below fails with an error:
```
SELECT
  *
FROM
  table1
WHERE
  true;
QUALIFY ROW_NUMBER() OVER (PARTITION BY TIMESTAMP_TRUNC(timestamp, HOUR), col1, col2 ORDER BY timestamp DESC) = 1
```

Error
```
ERROR: INVALID_ARGUMENT: Syntax error: Expected end of input but got keyword QUALIFY [at 7:1]
QUALIFY ROW_NUMBER() OVER (PARTITION BY TIMESTAMP_TRUNC(timestamp, HOUR), col...
^
```

Is it possible to support QUALIFY please?

**Comment by Matts966** [comment]
This is resolved by the version [v1.6.0](https://github.com/Matts966/zetasql-formatter/releases/tag/v1.6.0).
Thank you for your contribution!
