### ISSUE TITLE
Modify point

### ISSUE THREAD

**Issue by yun-cn** [Matts966/zetasql-formatter#2]
Thank you for developing such a useful tool.
I have a question. If there is **%** in the code, it is currently unavailable.

Example:

```
 -- "LatSa"
-- < Arguments >
-- [1]  : Da ID.
SELECT
  MAX(time) AS table_date
FROM
  %[1]s.users
WHERE
  status = 1;
```
Do you have any good suggestions

**Comment by Matts966** [comment]
@yun-cn 
Using ` just works.

```
 -- "LatestSim"
-- < Arguments >
-- [1]  : Dataset ID.
SELECT
  MAX(time) AS table_date
FROM
  `%[1]s.users`
WHERE
  status = 1;
```

Are you using some type of string substitution by yourself?
Or you use some tool for it? If you could, please teach me (just for my interest).

**Comment by yun-cn** [comment]
Using ` just works.
I see.  Thank you, guy.

Yes.
`//go:generate gobin -m -run github.com/tscholl2/embd -n sqlTemplate query.sql`

I converted the converted SQL file into a string.
Then use `fmt` to perform the replacement. 

Look likes  `fmt.Sprintf(sqlTemplate, datasetID)`

**Comment by yun-cn** [comment]
@Matts966 

```
    SELECT
        r.item_id,
        CAST(FLOOR(SUM(users.ca)) AS INT64) AS amo
    FROM
        users
        INNER JOIN languages AS r ON
            users.id = r.user_id AND
            users.priority '%[14]s' r.priority
    GROUP BY
        r.id
```

Sorry to bother you again.
Is there any good solution in this situation

Error:
`ERROR: INVALID_ARGUMENT: Syntax error: Expected end of input but got string literal '%[14]s'`

**Comment by Matts966** [comment]
@yun-cn 
Substituting syntax keywords can be difficult, I think.
They can be tokenized correctly, but the syntax is invalid. The string ident should be something like `>`.
I recommend that you use user defined functions like 

```sql
CREATE TEMP FUNCTION isHigher(x INT64, y INT64) AS (x > y);
CREATE TEMP FUNCTION isTheSame(x INT64, y INT64) AS (x = y);
CREATE TEMP FUNCTION isLower(x INT64, y INT64) AS (x < y);

SELECT
    r.item_id,
    CAST(FLOOR(SUM(users.ca)) AS INT64) AS amo
FROM
    users
    INNER JOIN languages AS r ON
        users.id = r.user_id AND
        `%[14]s`(users.priority, r.priority)
GROUP BY
    r.id;
```
