### ISSUE TITLE
Format WHERE and ON clauses with multiple conditions with new lines

### ISSUE THREAD

**Issue by codepozro** [Matts966/zetasql-formatter#6]
Hello @Matts966 !

I was wondering if it's at all possible to format `WHERE` and `ON` clauses with multiple conditions so that each line has a single condition. For example,

```sql
SELECT
  *
FROM
  foo.bar_tab
WHERE
  col1 = 'abc' 
  AND col2 > 10 
  AND col3 IS NOT NULL;
```

Currently `zetasql-formatter` formats above example as:

```sql
SELECT
  *
FROM
  foo.bar_tab
WHERE
  col1 = 'abc' AND col2 > 10 AND col3 IS NOT NULL;
```

Which makes it hard to see what's changed when only one of the conditions is updated.

**Comment by Matts966** [comment]
Thank you for your contribution!

I also recognize this problem and will work on it in a week.

**Comment by Matts966** [comment]
@codepozro 
This was fixed by the release `v1.5.7`. 
Thank you :tada:

**Comment by codepozro** [comment]
Thank you for a quick turnaround. I've just installed the latest following [the Quick Start](https://github.com/Matts966/zetasql-formatter#quick-start) and the new formatting looks great !

On a side note, is there a way to install a specific version? The Quick Start installed, I believe, the latest but it doesn't seem to have a version:

```
% zetasql-formatter --version
zetasql-formatter
Debug build (NDEBUG not #defined)
```

**Comment by Matts966** [comment]
I will track it in https://github.com/Matts966/zetasql-formatter/issues/11
Thanks!
